version: '3.1'
services:
  stats-server:
    build: stats-service
    container_name: stats-service
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db/stat_db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root


  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stat_db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - PGDATA=/var/lib/postgresql/data1
      - DB_HOST=localhost
      - DB_PORT=5431

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db
    ports:
      - "6542:5432"
    environment:
      - PGDATA=/var/lib/postgresql/data2
      - POSTGRES_DB=event_db
      - POSTGRES_USER=root1
      - POSTGRES_PASSWORD=root1
      - DB_HOST=localhost
      - DB_PORT=5432

  main-service:
    build: ewm-service
    container_name: event-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db/event_db
      - POSTGRES_USER=root1
      - POSTGRES_PASSWORD=root1
      - STATS-SERVER.ADDRESS=http://stats-server:9090