version: '3.1'
services:
  stats-server:
    build: stats-service
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stat_db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  stats-db:
    image: postgres:14-alpine
    container_name: 'stats_db'
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stat_db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  ewm-db:
    image: postgres:14-alpine
    container_name: 'event_db'
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=event_db
      - POSTGRES_USER=root1
      - POSTGRES_PASSWORD=root1